name: MSBuild

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .

  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }} ${{ env.SOLUTION_FILE_PATH }}

    - name: Upload artifact (EXE)
      uses: actions/upload-artifact@v4
      with:
        name: Minesweeper-${{ env.BUILD_PLATFORM }}
        path: bin/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_CONFIGURATION }}/Minesweeper.exe
        if-no-files-found: error

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_CONFIGURATION }}/Minesweeper.exe
        generate_release_notes: true
